/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
//
//
//@author: Andrea Contardi
// Account Manager: usato per gestire tutti gli account presenti nel file "utenti.txt"
// funzioni principali: cancellare, cercare utenti all'interno del file e riportarli in una tabella
*/
package compagniaaereahtml;

import static compagniaaereahtml.AdminFlightManager.cancellariga;
import java.awt.Color;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrea
 */
public class AccountManager extends javax.swing.JFrame {

    //metodo per rendere la tabella trasparente (preso da google)
    public static void makeTableTransparent(JTable table) {
        table.setOpaque(false);

        // Imposta il renderizzatore delle celle come trasparente
        ((DefaultTableCellRenderer)table.getDefaultRenderer(Object.class)).setOpaque(false);

        // Imposta lo sfondo delle righe come trasparente
        table.setBackground(new Color(0, 0, 0, 0));

        // Imposta lo sfondo delle celle selezionate come trasparente
        table.setSelectionBackground(new Color(0, 0, 0, 0));

        // Imposta lo sfondo del pannello di visualizzazione come trasparente
        JScrollPane scrollPane = (JScrollPane) table.getParent().getParent();
        scrollPane.setOpaque(false);
        scrollPane.getViewport().setOpaque(false);

        // Aggiorna la tabella per riflettere le modifiche
        table.repaint();
    }

    //metodo per leggere il file e caricare la tabella
    private void leggifile() {
    try {
        File myObj = new File("utenti.txt");
        Scanner myReader = new Scanner(myObj);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        while (myReader.hasNextLine()) {
            String riga = myReader.nextLine().trim(); // Rimuove gli spazi bianchi iniziali e finali

            if (!riga.isEmpty()) { // Ignora le righe vuote
                String[] campi = riga.split("\\s+"); // Utilizza un'espressione regolare per dividere la riga per spazi multipli
                if (campi.length >= 3) {
                    String uname = campi[0];
                    String password = campi[1];
                    String tipo = campi[2];
                    System.out.println(tipo);
                    model.addRow(new Object[]{uname, password, tipo});
                } else {
                    System.err.println("Riga non valida: " + riga);
                }
            }
        }

        myReader.close();
    } catch (FileNotFoundException e) {
        System.err.println("File non trovato: " + e.getMessage());
    }
}
    
    //metodo per cancellare una specifica riga del file (preso da google)
    public static boolean cancellariga(int lineNumberToDelete) {
        try {
            File inputFile = new File("utenti.txt");
            File tempFile = new File("temp2.txt");

            BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));

            String currentLine;
            int lineNumber = 1;

            while ((currentLine = reader.readLine()) != null) {
                if (lineNumber != lineNumberToDelete) {
                    writer.write(currentLine);
                    writer.newLine();
                }
                lineNumber++;
            }

            reader.close();
            writer.close();

            if (!inputFile.delete()) {
                System.out.println("Impossibile eliminare");
                return false;
            }
            if (!tempFile.renameTo(inputFile)) {
                System.out.println("Impossibile rinominare");
                return false;
            }

            return true;
        } 
         catch (IOException e) {
            System.out.println("Errore");
        }
        return false;
    }
    
    
    public AccountManager() {
        initComponents();
        leggifile();
        makeTableTransparent(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Account Manager");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);

        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Utente", "Password", "Tipo Account"
            }
        ));
        jTable1.setSelectionForeground(new java.awt.Color(102, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 55, 520, 460));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controlli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compagniaaereahtml/bin.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compagniaaereahtml/cerca.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 55, -1, 460));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compagniaaereahtml/uscita.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 47, 18));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compagniaaereahtml/acmanager.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 850, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //pulsante uscita
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SimulateUser().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //pulsante per rimuovere un utente sia dalla tabella che dal file
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        

        
        if (row>=0) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            if (model.getValueAt(row, 0).equals("master")) {
                JOptionPane.showMessageDialog(null, "NON puoi eliminare l'utente master", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int input = JOptionPane.showConfirmDialog(null, "Vuoi eliminare l'utente? (l'azione è IRREVERSIBILE)", "ELIMINA UTENTE", HEIGHT);
                System.out.println(input);
                if (input == 0) {
                     model.removeRow(row);
                        System.out.println("USER MANAGER: utente eliminato con successo");

                cancellariga(row+1);
                JOptionPane.showMessageDialog(null, "Utente Cancellato", "NOTICE", JOptionPane.INFORMATION_MESSAGE);

            }
         
        }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleziona una riga", "ERRORE", JOptionPane.ERROR_MESSAGE);
            System.out.println("FLIGHT MANAGER: impossibile eliminare l'utente");
            System.out.println("FLIGHT MANAGER: nessun utente selezionato");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
     
     //pulsante per la ricerca
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        boolean trovato = false;
        int i;
        System.out.println("USER MANAGER: inserire il nome utente");
        String codice = JOptionPane.showInputDialog("Inserisci il nome utente");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    for ( i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 0).equals(codice)) {
            System.out.println("USER MANAGER: utente trovato");
            trovato = true;
            String pw = (String) model.getValueAt(i, 1);
            String type = (String) model.getValueAt(i, 2);
            
            JOptionPane.showMessageDialog(null, "HO TROVATO L'UTENTE CON NOME UTENTE:" + codice + "\nPASSWORD: " + pw + "\nTipo:" + type , "RICERCA UTENTE" , JOptionPane.INFORMATION_MESSAGE);
        }
}

        if (trovato==false) {
            JOptionPane.showMessageDialog(null, "Nessun utente trovato con il codice: " + codice, "NOTICE", HEIGHT);
            System.out.println("USER MANAGER: nessun utente trovato");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
